import yaml
import os
import copy

BASE_CONFIG = "examples/train_full/telechat3_pt_cpu_350B.yaml"

def generate_configs():
    with open(BASE_CONFIG, 'r', encoding='utf-8') as f:
        config_content = f.read()
        # Simple string replacement might be safer than parsing if we want to preserve comments/structure, 
        # but parsing is safer for correctness. 
        # Since strict structure isn't critical for the runner (it just loads dict), let's try strict parsing first.
        # However, LlamaFactory might expect specific YAML structure.
        # Let's simple string replace for these specific keys since we know the file content.
    
    # Actually, let's use a safe loading approach if possible.
    # But string replacement is robust against "comments disappearing".
    
    # We will simply write new files based on the template.
    
    for i in range(1, 21):
        part_suffix = f"_part{i}"
        
        new_content = config_content
        
        # Replace dataset
        new_content = new_content.replace("dataset: fineweb_edu_350b", f"dataset: fineweb_edu_350b{part_suffix}")
        
        # Replace tokenized_path
        new_content = new_content.replace(
            "tokenized_path: tokenized_path/fineweb_edu_350b", 
            f"tokenized_path: tokenized_path/fineweb_edu_350b{part_suffix}"
        )
        
        # Replace output_dir
        new_content = new_content.replace(
            "output_dir: saves/telechat3-1p8b/pt/fineweb-edu-350b-cpu", 
            f"output_dir: saves/telechat3-1p8b/pt/fineweb-edu-350b-cpu{part_suffix}"
        )
        
        new_filename = BASE_CONFIG.replace(".yaml", f"{part_suffix}.yaml")
        
        with open(new_filename, 'w', encoding='utf-8') as f:
            f.write("# Auto-generated by generate_part_configs.py\n")
            f.write(new_content)
        
        print(f"Created {new_filename}")

if __name__ == "__main__":
    generate_configs()
