### model
model_name_or_path: Telechat3-1p8B
trust_remote_code: true

### method
stage: pt
do_train: true
finetuning_type: full

deepspeed: examples/deepspeed/ds_z2_config.json

### dataset
dataset: fineweb_edu_350b
cutoff_len: 4096
# max_samples: 100000
overwrite_cache: true
tokenized_path: tokenized_path/fineweb_edu_350b_merged
preprocessing_num_workers: 16

### output
output_dir: saves/telechat3-1p8b/pt/fineweb-edu-350b
logging_steps: 10
save_steps: 5000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
flash_attn: fa2

### FP8 configuration
fp8: true
fp8_backend: torchao  # Use TorchAO backend for FP8
fp8_enable_fsdp_float8_all_gather: false  # Not used with DeepSpeed


### eval
val_size: 0.01
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 500
